### ISSUE TITLE
Moveformatter uses capital B whenpawn on b-file captures

### ISSUE THREAD

**Issue by Fredrik-Lindner** [iigorr/pgn.net#11]
When a pawn on the b-file captures (e.g. bxc6) the formatter wil use captial B making the move Bxc6 denoting a capture by the bishop. I don't know if this occurs all the times a b-pawn captures but it does sometimes.

Example

Original pgn: (note blacks 9:th move)

[Event "DHLC Slow 1-2 Pairing #03"]
[Site "Live Chess on Chess.com"]
[Date "2013.11.16"]
[Round "2"]
[White "amichay"]
[Black "Alabasterknight"]
[Result "1-0"]
[ECO "C41"]
[WhiteElo "1220"]
[BlackElo "754"]
[Annotator "Lenning,Bob"]
[PlyCount "31"]
[EventDate "2013.??.??"]
[TimeControl "90"]
1. e4 e5 2. Nf3 d6 3. d4 Nf6 4. Nc3 Bg4 5. Bg5 Be7 6. h3 Bxf3 7. Qxf3 Nc6 8.
   Bb5 a6 9. Bxc6+ bxc6 10. dxe5 Nd7 11. Bxe7 Qxe7 12. exd6 Qxd6 13. Rd1 Qc5 14.
   Qg4 f5 15. Qxg7 Qf8 16. Qxd7# 1-0  

Output of game.ToString() (again note the (erronius) 9:th move of black:

"[Event \"DHLC Slow 1-2 Pairing #03\"]\r\n[Site \"Live Chess on Chess.com\"]\r\n[Date \"2013.11.16\"]\r\n[Round \"2\"]\r\n[White \"amichay\"]\r\n[Black \"Alabasterknight\"]\r\n[Result \"1-0\"]\r\n[ECO \"C41\"]\r\n[WhiteElo \"1220\"]\r\n[BlackElo \"754\"]\r\n[Annotator \"Lenning,Bob\"]\r\n[PlyCount \"31\"]\r\n[EventDate \"2013.??.??\"]\r\n[TimeControl \"90\"]\r\n\r\n1. e4 e5 2. Nf3 d6 3. d4 Nf6 4. Nc3 Bg4 5. Bg5 Be7 6. h3 Bxf3 7. Qxf3 Nc6 8. Bb5 a6 9. Bxc6+ Bxc6 10. dxe5 Nd7 11. Bxe7 Qxe7 12. exd6 Qxd6 13. Rd1 Qc5 14. Qg4 f5 15. Qxg7 Qf8 16. Qxd7# 1-0"

**Comment by Dodgero** [comment]
Hi iigorr, 

It seems this is still an issue. I have downloaded via nuget v1.1.1.0, and the bug is there when getting moves by .MoveText property. Also, another user signalized that the problem is still there yesterday. Could you please let me know if you could resolve this soon ? I'd appreciate that :)

Kind regards and thank you for this fine library!

**Comment by iigorr** [comment]
Hi Dodgero

Thanks for reporting! It seems that something went wrong with the package 1.1.1.0. The old broken parsers DLL was packed and I haven't noticed. Sorry for that. I have just published the fixed version as 1.1.1.1. Please let me know if there are any issues, I'll try to fix them asap.

Cheers,

Igor

**Comment by Dodgero** [comment]
Hi Igor,

This is great, thanks a lot! I will try it out.

Regarding issues, I don't know if what I am going to point out can be
called that way, but I have noticed the library does not support some of
the pgn header fields. I think it would be great if it would be possible to
access them via properties and to get on the output the same what was on
the input, so that no fields would be lost in the process. In other words,
after operation pgn->reader->writer->pgn, the pgn should be the same on
both sides. To make this happen, all headers would have to be processed,
now they are cut off. Namely, header fields "WhiteElo", "BlackElo" I find
as quite important.

Would you kindly consider adding support for other pgn header fields ? ;)

Cheers,
Dodgero

2015-06-10 23:34 GMT+02:00 Igor Lankin <notifications@github.com>:

**Comment by iigorr** [comment]
Hi Dodgero,

as the issue with the pawn interpreted as a bishop is hopefully closed, I have created a new issue https://github.com/iigorr/pgn.net/issues/13 for what you are suggesting. Let's discuss it there.

Cheers,

Igor
